name: Elasticsearch Deploy
description: Deploy an AWS Elasctisearch service cluster using Terraform
inputs:
  engine_version:
    description: 'Elasticsearch version number'
    default: '7.4'

  instance_type:
    description: 'AWS Instance Type to deploy the cluster'
    default: 't2.medium.elasticsearch'

  instance_count:
    description: 'How many instance will compound this cluster'
    default: '1'

  snapshot_hour:
    description: 'Hour during which the service takes an automated daily snapshot of the indices in the domain. UTC Time'
    default: '23'

  ebs:
    description: 'Support EBS Storage'
    default: true

  volume_type:
    description: 'Kind of storage to use (standard, gp2, io1)'
    default: 'gp2'

  volume_size:
    description: 'Size of the volume for ES Storage in gigs'
    default: 10

  log_type:
    description: 'A type of Elasticsearch log. Valid values: INDEX_SLOW_LOGS, SEARCH_SLOW_LOGS, ES_APPLICATION_LOGS'
    default: 'INDEX_SLOW_LOGS'

  public:
    description: 'Enable public ElasticSearch instance'
    default: false

  allowed_ips:
    description: 'List of IPs valid to connect to the cluster, separated by commas when [public only]'
    default: ''

outputs:
  arn:
    description: 'Elasticsearch service ARN'
  endpoint:
    description: 'Elasticsearch service endpoint'
  kibana_endpoint:
    description: 'Elasticsearch service Kibana endpoint'
  access_policy_arn:
    description: 'ARN of policy granting access to this ES instance'
  access_policy_name:
    description: 'Name of policy granting access to this ES instance'

runs:
  using: docker
  image: Dockerfile
