name: Elasticsearch Deploy
description: Deploy an AWS Elasctisearch service cluster using Terraform
inputs:
  workspace:
    description: 'Terraform Workspace'
    required: true

  project:
    description: 'Project this Service is part of'
    required: true

  owner:
    description: 'Project owner/team'
    required: true

  email:
    description: 'Project email address'
    required: true

  destroy:
    description: 'Runs Terraform destroy to destroy existing resources created by this action'
    required: false
    default: 'false'

  region:
    description: 'AWS region to deploy to'
    required: false
    default: 'us-west-2'

  es_domain:
    description: 'AWS Elasticsearch service domain'
    required: true

  es_version:
    description: 'Elasticsearch version number'
    required: true
    default: '7.4'

  es_instance_type:
    description: 'AWS Instance Type to deploy the cluster'
    default: 't2.medium.elasticsearch'
    required: true

  es_snapshot_hour:
    description: 'Hour during which the service takes an automated daily snapshot of the indices in the domain. UTC Time'
    default: '23'
    required: true

  es_ebs_enabled:
    description: 'Support EBS Storage'
    default: 'true'
    required: true

  es_volume_type:
    description: 'Kind of storage to use (standard, gp2, io1)'
    default: 'gp2'
    required: false

  es_volume_size:
    description: 'Size of the volume for ES Storage'
    default: 10
    required: false

outputs:
  es_arn:
    description: 'Name of the created function'
  
runs:
  using: docker
  image: Dockerfile